"""empty message

Revision ID: 516d3b9c3f05
Revises: 8c4809903e33
Create Date: 2019-08-22 11:40:27.235959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516d3b9c3f05'
down_revision = '8c4809903e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
