"""empty message

Revision ID: 74649dd4c36f
Revises: ce5201093874
Create Date: 2019-08-14 14:31:18.167667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74649dd4c36f'
down_revision = 'ce5201093874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_status', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_status')
    # ### end Alembic commands ###
