"""empty message

Revision ID: 80403563cfb8
Revises: a3834058c13c
Create Date: 2019-08-22 11:08:46.860264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80403563cfb8'
down_revision = 'a3834058c13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manager',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    # ### end Alembic commands ###
