"""empty message

Revision ID: 8443ea318dd5
Revises: a2cc04ed5d91
Create Date: 2019-08-18 20:04:31.327958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8443ea318dd5'
down_revision = 'a2cc04ed5d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_praise', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_praise')
    # ### end Alembic commands ###
