"""empty message

Revision ID: 9ddba3d2a1e0
Revises: e8a661589896
Create Date: 2019-08-13 15:51:19.435001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddba3d2a1e0'
down_revision = 'e8a661589896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('comment_ibfk_2', 'comment', 'user', ['parent_id'], ['id'])
    # ### end Alembic commands ###
