"""empty message

Revision ID: a2cc04ed5d91
Revises: 74649dd4c36f
Create Date: 2019-08-15 17:09:34.073808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2cc04ed5d91'
down_revision = '74649dd4c36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_picture', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'article_picture')
    # ### end Alembic commands ###
