"""empty message

Revision ID: b712e6a842d3
Revises: 091eb5dd6022
Create Date: 2019-08-19 18:54:08.797719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b712e6a842d3'
down_revision = '091eb5dd6022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('reply_comment_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'reply_comment_id')
    # ### end Alembic commands ###
